### ISSUE TITLE
Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'iteritems'

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/bareos-formula#22]
On Centos7 

with the pillar.example : 

```yaml
bareos:
  filedaemon:
    plugins:
      - bareos-filedaemon-python-plugin
      - bareos-filedaemon-glusterfs-plugin
    config:
      Director:
        bareos-dir:
          Description: The default BareOS director resource
        bareos-mon:
          Description: A monitor resource
          Monitor: true
      Client:
        bareos-fd:
          MaximumConcurrentJobs: 20
      Messages:
        Standard:
          Director: bareos-debian-jessie64-dir = all, !skipped, !restored
```

I get : 

```
local:
----------
          ID: bareos_fd_cfg_file
    Function: file.managed
        Name: /etc/bareos/bareos-fd.conf
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'iteritems'
     Started: 15:23:08.025129
    Duration: 64.926 ms
     Changes:   
----------
          ID: bareos_fd_service
    Function: service.running
        Name: bareos-fd
      Result: False
     Comment: One or more requisite failed: bareos.filedaemon.bareos_fd_cfg_file
     Started: 15:23:08.090959
    Duration: 0.003 ms
     Changes:   
```
versions : 

```
[vagrant@default-centos-7 ~]$ sudo salt-call test.versions_report
local:
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.33.0
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.4.2
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7.4.1708 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-693.21.1.el7.x86_64
             system: Linux
            version: CentOS Linux 7.4.1708 Core
```
